server:
  port: 0

spring:
  application:
    name: store-auth

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

store:
  jwt:
    issuer: store
    secret-key: hIiyhhEj2pNhV2p3Mk6tFhjiG4RObrhEhIiyhhEj2pNhV2p3Mk6tFhjiG4RObrhEhIiyhhEj2pNhV2p3Mk6tFhjiG4RObrhE
    duration: 31536000000 # 365 days in miliseconds